"""Train and evaluate the severity classifier.

    python -m app.ml.train            (from the backend/ directory)

Pipeline: synthetic dataset -> preprocessing -> stratified 80/20 split -> {LogisticRegression,
RandomForest, GradientBoosting} -> evaluation -> RandomForest saved with joblib -> loaded by the API.
"""
from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from app.ml.dataset import CATEGORICAL_FEATURES, CLASSES, FEATURES, NUMERIC_FEATURES, generate

ML_DIR = Path(__file__).resolve().parent
ARTIFACTS = ML_DIR / "artifacts"
MODEL_PATH = ARTIFACTS / "model.joblib"
METRICS_PATH = ARTIFACTS / "metrics.json"
DATA_PATH = ML_DIR / "data" / "synthetic_emergencies.csv"


def build(model_name: str, seed: int, numeric=NUMERIC_FEATURES, categorical=CATEGORICAL_FEATURES) -> Pipeline:
    scale = model_name == "logistic_regression"
    steps = [("impute", SimpleImputer(strategy="median"))]   # real datasets have missing vitals
    if scale:
        steps.append(("scale", StandardScaler()))
    transformers = [("num", Pipeline(steps), list(numeric))]
    if categorical:
        transformers.append(("cat", OneHotEncoder(handle_unknown="ignore"), list(categorical)))
    pre = ColumnTransformer(transformers)
    if model_name == "logistic_regression":
        clf = LogisticRegression(max_iter=2000, random_state=seed)
    elif model_name == "random_forest":
        clf = RandomForestClassifier(n_estimators=200, max_depth=14, min_samples_leaf=2, class_weight="balanced",
                                     random_state=seed, n_jobs=-1)
    elif model_name == "gradient_boosting":
        clf = GradientBoostingClassifier(random_state=seed)
    else:
        raise ValueError(model_name)
    return Pipeline([("pre", pre), ("clf", clf)])


def evaluate(pipe: Pipeline, x_test, y_test) -> dict:
    pred = pipe.predict(x_test)
    p, r, f, _ = precision_recall_fscore_support(y_test, pred, labels=CLASSES, average="macro", zero_division=0)
    return {
        "accuracy": round(float(accuracy_score(y_test, pred)), 4),
        "precision_macro": round(float(p), 4), "recall_macro": round(float(r), 4), "f1_macro": round(float(f), 4),
        "confusion_matrix": {"labels": CLASSES, "matrix": confusion_matrix(y_test, pred, labels=CLASSES).tolist()},
        "per_class": classification_report(y_test, pred, labels=CLASSES, output_dict=True, zero_division=0),
    }


DATASET_INFO = {
    "synthetic": "SYNTHETIC medically-inspired cases generated by app/ml/dataset.py (academic demonstration only)",
    "ktas": "REAL ED triage data: Moon et al. 2019, PLOS ONE 14(9):e0216972 (KTAS, Korea, CC BY 4.0); "
            "KTAS 1-5 mapped to CRITICAL/HIGH/MEDIUM/LOW",
    "mimic-ed": "REAL ED triage data: MIMIC-IV-ED triage table (PhysioNet credentialed access); ESI 1-5 mapped to 4 classes",
}


def main(n: int = 6000, seed: int = 42, quiet: bool = False, dataset: str = "synthetic", data_path: str | None = None,
         model_path: Path = MODEL_PATH, metrics_path: Path = METRICS_PATH) -> dict:
    if dataset == "synthetic":
        df = generate(n=n, seed=seed)
        DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(DATA_PATH, index=False)
        feats, numeric, categorical = FEATURES, NUMERIC_FEATURES, CATEGORICAL_FEATURES
    else:
        from app.ml.real_datasets import LOADERS, REAL_FEATURES
        if not data_path or not Path(data_path).exists():
            raise SystemExit(f"--data must point to the downloaded {dataset} CSV (got {data_path!r})")
        df = LOADERS[dataset](data_path)
        feats, numeric, categorical = REAL_FEATURES, REAL_FEATURES, []
    present = [c for c in CLASSES if (df["severity"] == c).sum() >= 2]
    df = df[df["severity"].isin(present)]
    x, y = df[feats], df["severity"]
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=seed)
    results = {}
    pipes = {}
    for name in ("logistic_regression", "random_forest", "gradient_boosting"):
        t0 = time.perf_counter()
        pipe = build(name, seed, numeric, categorical).fit(x_train, y_train)
        res = evaluate(pipe, x_test, y_test)
        res["train_seconds"] = round(time.perf_counter() - t0, 2)
        results[name] = res
        pipes[name] = pipe
        if not quiet:
            print(f"{name:22s} acc={res['accuracy']:.4f} P={res['precision_macro']:.4f} "
                  f"R={res['recall_macro']:.4f} F1={res['f1_macro']:.4f} ({res['train_seconds']}s)")
    deployed = "random_forest"
    rf: Pipeline = pipes[deployed]
    names = rf.named_steps["pre"].get_feature_names_out()
    importances = sorted(zip([n.split("__", 1)[1] for n in names], rf.named_steps["clf"].feature_importances_),
                         key=lambda t: -t[1])
    version = datetime.now(timezone.utc).strftime("rf-%Y%m%d%H%M%S")
    Path(model_path).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"pipeline": rf, "classes": CLASSES, "features": list(feats), "version": version,
                 "model_name": "RandomForestClassifier", "dataset": dataset}, model_path)
    report = {
        "disclaimer": ("Synthetic, medically-inspired data for academic demonstration only. Not clinically validated."
                       if dataset == "synthetic" else
                       "Trained on a real, public ED triage dataset for academic purposes. It reproduces triage "
                       "levels assigned by clinicians in that dataset; it is NOT a validated medical device."),
        "dataset": {"name": dataset, "description": DATASET_INFO[dataset], "rows": len(df), "seed": seed,
                    "class_counts": df["severity"].value_counts().to_dict(),
                    "train_rows": len(x_train), "test_rows": len(x_test), "split": "80/20 stratified"},
        "deployed_model": deployed, "version": version, "models": results,
        "feature_importances": [{"feature": f, "importance": round(float(v), 4)} for f, v in importances[:15]],
    }
    Path(metrics_path).write_text(json.dumps(report, indent=2))
    if not quiet:
        cm = np.array(results[deployed]["confusion_matrix"]["matrix"])
        print("RandomForest confusion matrix (rows=true, cols=pred)", CLASSES)
        print(cm)
        print(f"saved {model_path} ({version})")
    return report


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=6000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--dataset", choices=["synthetic", "ktas", "mimic-ed"], default="synthetic")
    ap.add_argument("--data", help="path to the downloaded real dataset CSV (ktas: data.csv, mimic-ed: triage.csv)")
    a = ap.parse_args()
    main(a.rows, a.seed, dataset=a.dataset, data_path=a.data)
