"""Train and evaluate the severity classifier.

    python -m app.ml.train            (from the backend/ directory)

Pipeline: synthetic dataset -> preprocessing -> stratified 80/20 split -> {LogisticRegression,
RandomForest, GradientBoosting} -> evaluation -> probability calibration check (app/ml/calibration.py) ->
RandomForest (calibrated only if that measurably improves held-out probabilities) saved with joblib -> API.
"""
from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from app.ml.dataset import CATEGORICAL_FEATURES, CLASSES, FEATURES, NUMERIC_FEATURES, generate

ML_DIR = Path(__file__).resolve().parent
ARTIFACTS = ML_DIR / "artifacts"
MODEL_PATH = ARTIFACTS / "model.joblib"
METRICS_PATH = ARTIFACTS / "metrics.json"
DATA_PATH = ML_DIR / "data" / "synthetic_emergencies.csv"


def build(model_name: str, seed: int, numeric=NUMERIC_FEATURES, categorical=CATEGORICAL_FEATURES) -> Pipeline:
    scale = model_name == "logistic_regression"
    steps = [("impute", SimpleImputer(strategy="median"))]   # real datasets have missing vitals
    if scale:
        steps.append(("scale", StandardScaler()))
    transformers = [("num", Pipeline(steps), list(numeric))]
    if categorical:
        transformers.append(("cat", OneHotEncoder(handle_unknown="ignore"), list(categorical)))
    pre = ColumnTransformer(transformers)
    if model_name == "logistic_regression":
        clf = LogisticRegression(max_iter=2000, random_state=seed)
    elif model_name == "random_forest":
        clf = RandomForestClassifier(n_estimators=200, max_depth=14, min_samples_leaf=2, class_weight="balanced",
                                     random_state=seed, n_jobs=-1)
    elif model_name == "gradient_boosting":
        clf = GradientBoostingClassifier(random_state=seed)
    else:
        raise ValueError(model_name)
    return Pipeline([("pre", pre), ("clf", clf)])


def evaluate(pipe: Pipeline, x_test, y_test) -> dict:
    pred = pipe.predict(x_test)
    p, r, f, _ = precision_recall_fscore_support(y_test, pred, labels=CLASSES, average="macro", zero_division=0)
    return {
        "accuracy": round(float(accuracy_score(y_test, pred)), 4),
        "precision_macro": round(float(p), 4), "recall_macro": round(float(r), 4), "f1_macro": round(float(f), 4),
        "confusion_matrix": {"labels": CLASSES, "matrix": confusion_matrix(y_test, pred, labels=CLASSES).tolist()},
        "per_class": classification_report(y_test, pred, labels=CLASSES, output_dict=True, zero_division=0),
    }


DATASET_INFO = {
    "synthetic": "SYNTHETIC medically-inspired cases generated by app/ml/dataset.py (academic demonstration only)",
    "ktas": "REAL ED triage data: Moon et al. 2019, PLOS ONE 14(9):e0216972 (KTAS, Korea, CC BY 4.0); "
            "KTAS 1-5 mapped to CRITICAL/HIGH/MEDIUM/LOW",
    "mimic-ed": "REAL ED triage data: MIMIC-IV-ED triage table (PhysioNet credentialed access); ESI 1-5 mapped to 4 classes",
}


def main(n: int = 6000, seed: int = 42, quiet: bool = False, dataset: str = "synthetic", data_path: str | None = None,
         model_path: Path = MODEL_PATH, metrics_path: Path = METRICS_PATH, summary_path: Path | None = None) -> dict:
    if dataset == "synthetic":
        df = generate(n=n, seed=seed)
        DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(DATA_PATH, index=False)
        feats, numeric, categorical = FEATURES, NUMERIC_FEATURES, CATEGORICAL_FEATURES
    else:
        from app.ml.real_datasets import LOADERS, REAL_FEATURES
        if not data_path or not Path(data_path).exists():
            raise SystemExit(f"--data must point to the downloaded {dataset} CSV (got {data_path!r})")
        df = LOADERS[dataset](data_path)
        feats, numeric, categorical = REAL_FEATURES, REAL_FEATURES, []
    present = [c for c in CLASSES if (df["severity"] == c).sum() >= 2]
    df = df[df["severity"].isin(present)]
    x, y = df[feats], df["severity"]
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=seed)
    results = {}
    pipes = {}
    for name in ("logistic_regression", "random_forest", "gradient_boosting"):
        t0 = time.perf_counter()
        pipe = build(name, seed, numeric, categorical).fit(x_train, y_train)
        res = evaluate(pipe, x_test, y_test)
        res["train_seconds"] = round(time.perf_counter() - t0, 2)
        results[name] = res
        pipes[name] = pipe
        if not quiet:
            print(f"{name:22s} acc={res['accuracy']:.4f} P={res['precision_macro']:.4f} "
                  f"R={res['recall_macro']:.4f} F1={res['f1_macro']:.4f} ({res['train_seconds']}s)")
    deployed = "random_forest"
    rf: Pipeline = pipes[deployed]
    # probability calibration (model confidence quality, NOT clinical certainty) - see app/ml/calibration.py
    from app.ml.calibration import calibrate, probability_metrics
    x_fit, x_cal, y_fit, y_cal = train_test_split(x_train, y_train, test_size=0.25, stratify=y_train, random_state=seed)
    base = build(deployed, seed, numeric, categorical).fit(x_fit, y_fit)
    calibrated, cal_report = calibrate(base, x_cal, y_cal, x_test, y_test)
    cal_report["deployed_raw_model_full_train"] = probability_metrics(y_test, rf.predict_proba(x_test), list(rf.classes_))
    if not quiet:
        print(f"calibration: {cal_report['status']} ({cal_report.get('method')}) - {cal_report['reason']}")
    names = rf.named_steps["pre"].get_feature_names_out()
    importances = sorted(zip([n.split("__", 1)[1] for n in names], rf.named_steps["clf"].feature_importances_),
                         key=lambda t: -t[1])
    version = datetime.now(timezone.utc).strftime("rf-%Y%m%d%H%M%S")
    Path(model_path).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"pipeline": calibrated if calibrated is not None else rf,
                 "raw_pipeline": base if calibrated is not None else None,
                 "calibration": {**{k: cal_report.get(k) for k in ("status", "method", "reason")},
                                 "version": f"{version}-{cal_report.get('method')}" if calibrated is not None else None},
                 "classes": CLASSES, "features": list(feats), "version": version,
                 "model_name": "RandomForestClassifier", "dataset": dataset}, model_path)
    report = {
        "disclaimer": ("Synthetic, medically-inspired data for academic demonstration only. Not clinically validated."
                       if dataset == "synthetic" else
                       "Trained on a real, public ED triage dataset for academic purposes. It reproduces triage "
                       "levels assigned by clinicians in that dataset; it is NOT a validated medical device."),
        "dataset": {"name": dataset, "description": DATASET_INFO[dataset], "rows": len(df), "seed": seed,
                    "class_counts": df["severity"].value_counts().to_dict(),
                    "train_rows": len(x_train), "test_rows": len(x_test), "split": "80/20 stratified"},
        "deployed_model": deployed, "version": version, "models": results, "calibration": cal_report,
        "feature_importances": [{"feature": f, "importance": round(float(v), 4)} for f, v in importances[:15]],
    }
    Path(metrics_path).write_text(json.dumps(report, indent=2))
    if summary_path is None:      # a non-default training run (tests, experiments) must not overwrite the deployed summary
        summary_path = CALIBRATION_SUMMARY if Path(metrics_path) == METRICS_PATH else \
            Path(metrics_path).with_name("severity_calibration.json")
    write_calibration_summary(cal_report, version, dataset, len(y_test), quiet, summary_path)
    if not quiet:
        cm = np.array(results[deployed]["confusion_matrix"]["matrix"])
        print("RandomForest confusion matrix (rows=true, cols=pred)", CLASSES)
        print(cm)
        print(f"saved {model_path} ({version})")
    return report


CALIBRATION_SUMMARY = ML_DIR.parents[2] / "evaluation" / "severity_calibration.json"


def write_calibration_summary(rep: dict, version: str, dataset: str, n_test: int, quiet: bool,
                              path: Path | None = None) -> dict:
    """Machine-readable raw-vs-calibrated comparison on the untouched test split (values computed here, not typed)."""
    from app.ml.calibration import N_BINS
    from app.utils.logging import log_event
    raw, cal = rep["raw"], rep.get("calibrated")
    pick = cal if rep["status"] == "APPLIED" else raw
    out = {"model_version": version, "dataset": dataset, "status": rep["status"], "calibration_method": rep.get("method"),
           "calibration_version": f"{version}-{rep.get('method')}" if rep["status"] == "APPLIED" else None,
           "reason": rep["reason"],
           "split": "train 60 % / calibration 20 % / untouched test 20 % (stratified); calibration fitted on the "
                    "calibration part only; all metrics on the untouched test part",
           "sample_count": n_test, "calibration_sample_count": rep["calibration_rows"],
           "ece_bins": f"{N_BINS} equal-width bins of the top-label confidence (0-0.1, ..., 0.9-1.0)",
           "deployed_probabilities": "calibrated" if rep["status"] == "APPLIED" else "raw",
           "accuracy": pick["accuracy"], "precision": pick["precision_macro"], "recall": pick["recall_macro"],
           "f1": pick["f1_macro"],
           "brier_score_raw": raw["brier_multiclass"], "brier_score_calibrated": cal["brier_multiclass"] if cal else None,
           "ece_raw": raw["ece_top_label"], "ece_calibrated": cal["ece_top_label"] if cal else None,
           "raw": raw, "calibrated": cal,
           "note": ("synthetic data: metrics describe the generator, not clinical performance" if dataset == "synthetic"
                    else "public ED triage data: reproduces the dataset's triage labels; not clinically validated")}
    path = Path(path or CALIBRATION_SUMMARY)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2))
    log_event(__import__("logging").getLogger("app.ml"), "CALIBRATION_EVALUATED", status=out["status"],
              method=out["calibration_method"], brier_raw=out["brier_score_raw"], brier_cal=out["brier_score_calibrated"],
              ece_raw=out["ece_raw"], ece_cal=out["ece_calibrated"], samples=n_test)
    if not quiet:
        print(f"wrote {path}")
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=6000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--dataset", choices=["synthetic", "ktas", "mimic-ed"], default="synthetic")
    ap.add_argument("--data", help="path to the downloaded real dataset CSV (ktas: data.csv, mimic-ed: triage.csv)")
    a = ap.parse_args()
    main(a.rows, a.seed, dataset=a.dataset, data_path=a.data)
